FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 4200
CMD ["sh", "-c", "rm -rf .angular/cache && npx ng serve --host 0.0.0.0 --port 4200 --configuration development --poll 2000"]
