spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: LibraryService
  servlet:
    multipart:
      max-file-size: 10MB #Limite singolo file
      max-request-size: 50MB #Limite totale
  data:
    web:
      pageable:
        serialization-mode: via_dto
server:
  port: 8085
  servlet:
    context-path: /api/library
