spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: LibraryService
  data:
    web:
      pageable:
        serialization-mode: via_dto
server:
  port: 8085
  servlet:
    context-path: /api/library