FROM maven:3.9-eclipse-temurin-21
WORKDIR /workspace/GatewayService

EXPOSE 8083
CMD ["mvn", "-DskipTests", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]